# Generated by Django 4.1.1 on 2022-11-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.CharField(max_length=120)),
                ('nome', models.CharField(max_length=25)),
                ('ultimo_nome', models.CharField(max_length=25)),
                ('celular', models.CharField(max_length=10)),
                ('comentario', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=120)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=25)),
                ('senha', models.CharField(max_length=16)),
                ('nome', models.CharField(max_length=25)),
                ('ultimo_nome', models.CharField(max_length=25)),
                ('celular', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos_preenchido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salaoapp.agendamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salaoapp.servicos')),
            ],
        ),
        migrations.AddField(
            model_name='servicos',
            name='preenchido',
            field=models.ManyToManyField(through='Salaoapp.Servicos_preenchido', to='Salaoapp.agendamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salaoapp.usuario'),
        ),
    ]
