# Generated by Django 4.1.1 on 2022-11-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=25)),
                ('senha', models.CharField(max_length=16)),
                ('nome', models.CharField(max_length=25)),
                ('ultimo_nome', models.CharField(max_length=25)),
                ('celular', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('nome', models.CharField(max_length=25)),
                ('ultimo_nome', models.CharField(max_length=25)),
                ('celular', models.CharField(max_length=10)),
                ('comentario', models.TextField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salaoapp.usuario')),
            ],
        ),
    ]
