# Generated by Django 4.1.1 on 2022-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salaoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=45)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=25),
        ),
    ]
