# Generated by Django 4.1.1 on 2022-11-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salaoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora',
            field=models.CharField(max_length=120),
        ),
    ]
