# Generated by Django 4.1.1 on 2022-10-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salaoapp', '0002_endereco_usuario_celular_alter_usuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
