# Generated by Django 4.1.1 on 2022-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salaoapp', '0002_alter_agendamento_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='comentario',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
