# Generated by Django 4.1.1 on 2022-10-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salaoapp', '0003_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=14),
        ),
    ]
