# Generated by Django 4.1.1 on 2022-11-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salaoapp', '0003_alter_agendamento_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='corte',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='depilacao',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='limpeza',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='manicure',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='pedicure',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='pentado',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='sobrancelha',
        ),
    ]
